version: '3.4'

services:

  sqldata:
    image:  mysql:5.7
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      LC_ALL: C.UTF-8
      MYSQL_ROOT_PASSWORD: rootpwd
      MYSQL_USER: sysdba
      MYSQL_PASSWORD: dbapwd
    volumes:
      - ./.docker/mysql/mysqldata:/var/lib/mysql
      - ./.docker/mysql/dbinit:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 3306:3306
    networks:
      - sigo.dmz

  mysql-adminer:
    image: adminer
    container_name: mysql-adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - sqldata
    networks:
      - sigo.dmz

  gateway.api:
    image: ${DOCKER_REGISTRY-}apigateway
    container_name: apigateway
    build:
      context: .
      dockerfile: src/ApiGateways/APIGateway/Dockerfile
    ports:
      - 5000:80
      - 5001:443
    links:
      - autenticacao.api
      - processoindustrial.api
      - normas.api
      - consultorias.api
    networks:
      - sigo.dmz

  autenticacao.api:
    image: ${DOCKER_REGISTRY-}autenticacaoapi
    container_name: autenticacao
    build:
      context: .
      dockerfile: src/Services/Autenticacao/Autenticacao.API/Dockerfile
    depends_on:
      - sqldata
    ports:
      - 5100:80
      - 5101:443
    links:
      - sqldata
    networks:
      - sigo.dmz
      
  processoindustrial.api:
    image: ${DOCKER_REGISTRY-}processoindustrialapi
    container_name: processoindustrial
    build:
      context: .
      dockerfile: src/Services/ProcessoIndustrial/ProcessoIndustrial.API/Dockerfile
    depends_on:
      - sqldata
    ports:
      - 5200:80
      - 5201:443
    links:
      - sqldata
    networks:
      - sigo.dmz

  normas.api:
    image: ${DOCKER_REGISTRY-}normasapi
    container_name: normas
    build:
      context: .
      dockerfile: src/Services/Normas/Normas.API/Dockerfile
    depends_on:
      - sqldata
    ports:
      - 5300:80
      - 5301:443
    links:
      - sqldata
    networks:
      - sigo.dmz

  consultorias.api:
    image: ${DOCKER_REGISTRY-}consultoriasapi
    container_name: consultorias
    build:
      context: .
      dockerfile: src/Services/Consultorias/Consultorias.API/Dockerfile
    depends_on:
      - sqldata
    ports:
      - 5400:80
      - 5401:443
    links:
      - sqldata
    networks:
      - sigo.dmz

volumes:
  mysqldata:

networks:
  sigo.dmz:
