// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGO.Consultorias.Infrastructure.Data.Context;

namespace SIGO.Consultorias.Infrastructure.Data.Migrations
{
    [DbContext(typeof(MySqlContext))]
    partial class MySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SIGO.Consultorias.Domain.Entities.Consultoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Consultorias");

                    b.HasIndex("Nome")
                        .HasDatabaseName("Idx_Nome");

                    b.ToTable("consultorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataCriacao = new DateTime(2021, 3, 9, 13, 5, 55, 170, DateTimeKind.Local).AddTicks(4947),
                            Descricao = "Descrição Cosnsultoria 1",
                            Nome = "Consultoria 1"
                        },
                        new
                        {
                            Id = 2,
                            DataCriacao = new DateTime(2021, 3, 9, 13, 5, 55, 170, DateTimeKind.Local).AddTicks(6406),
                            Descricao = "Descrição Cosnsultoria 2",
                            Nome = "Consultoria 2"
                        });
                });

            modelBuilder.Entity("SIGO.Consultorias.Domain.Entities.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ConsultoriaID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataExclusao")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK_Contratos");

                    b.HasIndex("ConsultoriaID");

                    b.HasIndex("Nome")
                        .HasDatabaseName("Idx_Nome");

                    b.ToTable("contratos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConsultoriaID = 1,
                            DataCriacao = new DateTime(2021, 3, 9, 13, 5, 55, 171, DateTimeKind.Local).AddTicks(9789),
                            Descricao = "Descrição Contrato 1",
                            Nome = "Contrato 1",
                            Tipo = 0
                        },
                        new
                        {
                            Id = 2,
                            ConsultoriaID = 2,
                            DataCriacao = new DateTime(2021, 3, 9, 13, 5, 55, 172, DateTimeKind.Local).AddTicks(1597),
                            Descricao = "Descrição Contrato 2",
                            Nome = "Contrato 2",
                            Tipo = 1
                        },
                        new
                        {
                            Id = 3,
                            ConsultoriaID = 2,
                            DataCriacao = new DateTime(2021, 3, 9, 13, 5, 55, 172, DateTimeKind.Local).AddTicks(1603),
                            Descricao = "Descrição Contrato 3",
                            Nome = "Contrato 3",
                            Tipo = 32767
                        });
                });

            modelBuilder.Entity("SIGO.Consultorias.Domain.Entities.Contrato", b =>
                {
                    b.HasOne("SIGO.Consultorias.Domain.Entities.Consultoria", "Consultoria")
                        .WithMany("Contratos")
                        .HasForeignKey("ConsultoriaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Consultoria");
                });

            modelBuilder.Entity("SIGO.Consultorias.Domain.Entities.Consultoria", b =>
                {
                    b.Navigation("Contratos");
                });
#pragma warning restore 612, 618
        }
    }
}
